# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8dfa07252daf9404126943217f6957003a5349d1858fc798e04974f0938c11f2c916f8cb2c10cd8e9018681f4a33b2319ecc718ffe16c52a557ba31c9bf18cd

test:
  secret_key_base: e13ed0c6e7ccbc95eda8ee3da3090f630369b61f2b3bdf73e6b194d41ef3dc867ef0c5164fc83365f7f6461531da4b18603cc7eb894dcdad2b19e3720a9e91db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
